spring.application.name=staj1

spring.datasource.url=jdbc:postgresql://localhost:5432/staj1
spring.datasource.username=postgres
spring.datasource.password=heypardon0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true